export const getConstellations = (isMobile) => ({
  orion: {
    name: "Orion",
    stars: [
      {
        x: isMobile ? 15 : 20,
        y: isMobile ? 20 : 25,
        size: isMobile ? 2.5 : 3.5,
        opacity: 1,
        name: isMobile ? null : "Betelgeuse",
        color: "rgba(255, 100, 100, 1)",
      },
      {
        x: isMobile ? 15 : 20,
        y: isMobile ? 35 : 40,
        size: isMobile ? 2 : 2.8,
        opacity: 0.9,
      },
      {
        x: isMobile ? 25 : 30,
        y: isMobile ? 25 : 30,
        size: isMobile ? 2.2 : 3.2,
        opacity: 0.95,
      },
      {
        x: isMobile ? 25 : 30,
        y: isMobile ? 40 : 45,
        size: isMobile ? 1.8 : 2.5,
        opacity: 0.85,
      },
      {
        x: isMobile ? 35 : 40,
        y: isMobile ? 30 : 35,
        size: isMobile ? 2 : 3,
        opacity: 0.9,
      },
      {
        x: isMobile ? 35 : 40,
        y: isMobile ? 15 : 20,
        size: isMobile ? 2.5 : 3.5,
        opacity: 1,
        name: isMobile ? null : "Rigel",
        color: "rgba(100, 150, 255, 1)",
      },
    ],
    connections: [
      [0, 1],
      [1, 2],
      [2, 3],
      [3, 4],
      [4, 5],
      [2, 5],
    ],
  },
  ursaMajor: {
    name: "Ursa Major",
    stars: [
      {
        x: isMobile ? 55 : 65,
        y: isMobile ? 10 : 15,
        size: isMobile ? 2 : 3,
        opacity: 0.95,
      },
      {
        x: isMobile ? 60 : 70,
        y: isMobile ? 15 : 20,
        size: isMobile ? 1.8 : 2.5,
        opacity: 0.85,
      },
      {
        x: isMobile ? 65 : 75,
        y: isMobile ? 20 : 25,
        size: isMobile ? 2 : 2.8,
        opacity: 0.9,
      },
      {
        x: isMobile ? 70 : 80,
        y: isMobile ? 25 : 30,
        size: isMobile ? 2.2 : 3,
        opacity: 0.95,
      },
      {
        x: isMobile ? 75 : 85,
        y: isMobile ? 30 : 35,
        size: isMobile ? 1.8 : 2.5,
        opacity: 0.85,
      },
      {
        x: isMobile ? 80 : 90,
        y: isMobile ? 35 : 40,
        size: isMobile ? 2.2 : 3.2,
        opacity: 1,
      },
      {
        x: isMobile ? 85 : 95,
        y: isMobile ? 40 : 45,
        size: isMobile ? 2.5 : 3.5,
        opacity: 1,
        name: isMobile ? null : "Alkaid",
        color: "rgba(255, 255, 200, 1)",
      },
    ],
    connections: [
      [0, 1],
      [1, 2],
      [2, 3],
      [3, 4],
      [4, 5],
      [5, 6],
    ],
  },
  lyra: {
    name: "Lyra",
    stars: [
      {
        x: isMobile ? 20 : 25,
        y: isMobile ? 65 : 70,
        size: isMobile ? 2.8 : 3.8,
        opacity: 1,
        name: isMobile ? null : "Vega",
        color: "rgba(150, 200, 255, 1)",
      },
      {
        x: isMobile ? 15 : 20,
        y: isMobile ? 70 : 75,
        size: isMobile ? 1.8 : 2.5,
        opacity: 0.8,
      },
      {
        x: isMobile ? 25 : 30,
        y: isMobile ? 70 : 75,
        size: isMobile ? 1.8 : 2.5,
        opacity: 0.8,
      },
      {
        x: isMobile ? 20 : 25,
        y: isMobile ? 75 : 80,
        size: isMobile ? 1.8 : 2.5,
        opacity: 0.8,
      },
    ],
    connections: [
      [0, 1],
      [0, 2],
      [0, 3],
      [1, 2],
      [2, 3],
      [3, 1],
    ],
  },
  scorpius: {
    name: "Scorpius",
    stars: [
      {
        x: isMobile ? 60 : 70,
        y: isMobile ? 65 : 70,
        size: isMobile ? 2.5 : 3.5,
        opacity: 1,
        name: isMobile ? null : "Antares",
        color: "rgba(255, 150, 100, 1)",
      },
      {
        x: isMobile ? 65 : 75,
        y: isMobile ? 60 : 65,
        size: isMobile ? 1.8 : 2.5,
        opacity: 0.8,
      },
      {
        x: isMobile ? 70 : 80,
        y: isMobile ? 55 : 60,
        size: isMobile ? 1.8 : 2.5,
        opacity: 0.8,
      },
      {
        x: isMobile ? 75 : 85,
        y: isMobile ? 50 : 55,
        size: isMobile ? 1.8 : 2.5,
        opacity: 0.8,
      },
      {
        x: isMobile ? 80 : 90,
        y: isMobile ? 45 : 50,
        size: isMobile ? 1.8 : 2.5,
        opacity: 0.8,
      },
      {
        x: isMobile ? 75 : 85,
        y: isMobile ? 70 : 75,
        size: isMobile ? 1.8 : 2.5,
        opacity: 0.8,
      },
      {
        x: isMobile ? 70 : 80,
        y: isMobile ? 75 : 80,
        size: isMobile ? 1.8 : 2.5,
        opacity: 0.8,
      },
    ],
    connections: [
      [0, 1],
      [1, 2],
      [2, 3],
      [3, 4],
      [0, 5],
      [5, 6],
    ],
  },
});
