export const spaceKeywords = [
  "space", "galaxy", "planet", "star", "universe", "astronomy", "cosmos",
  "solar system", "black hole", "wormhole", "nebula", "quasar", "pulsar",
  "supernova", "dark matter", "dark energy", "event horizon", "accretion disk",
  "exoplanet", "red giant", "white dwarf", "neutron star", "magnetar", "big bang",
  "cosmic microwave background", "gamma-ray bursts", "interstellar", "intergalactic",
  "milky way", "andromeda", "spiral galaxy", "elliptical galaxy", "dwarf planet",
  "space exploration", "nasa", "spacex", "blue origin", "mars rover",
  "lunar eclipse", "solar eclipse", "international space station", "iss",
  "hubble telescope", "james webb telescope", "voyager 1", "voyager 2", "earth",
  "astrobiology", "extraterrestrial life", "search for extraterrestrial intelligence", "pluto",
  "seti", "zero gravity", "microgravity", "terraforming", "space colony",
  "stellar evolution", "gravity assist", "cosmic radiation", "stellar spectroscopy",
  "lunar gateway", "rocket science", "plasma propulsion", "solar sail",
  "space debris", "satellite constellation", "planetary transits", "exoplanet detection",
  "astrocartography", "space tourism", "future space missions", "astroengineering", "astronaut", 
  "cosmonaut", "orbital", "orbit", "celestial", "meteor", "meteorite", "meteoroid", "comet", "asteroid",  
  "kuiper belt", "oort cloud", "exosphere", "thermosphere", "mesosphere", "stratosphere", "troposphere", 
  "gravitational lensing", "light-year", "parsec", "astronomical unit", "cosmic web", "supercluster", 
  "local group", "virgo cluster", "laniakea", "hypernova", "protoplanetary disk", "protoplanet", "planetesimal", 
  "tidal locking", "tidal force", "orbital resonance", "lagrange point", "trojan asteroid", "brown dwarf", 
  "protostar", "stellar nursery", "stellar remnant", "event horizon telescope", "hawking radiation", "cosmic strings", 
  "graviton", "inflation theory", "multiverse", "parallel universe", "wormhole travel", "antimatter", "quark", 
  "neutrino", "pulsar wind", "x-ray binary", "gamma-ray astronomy", "space probe", "deep space", "interstellar medium", 
  "cosmic dust", "dark flow", "hot jupiter", "cold jupiter", "rogue planet", "tidal heating", "trappist-1", "kepler telescope", 
  "tess telescope", "exomoon", "exobiology", "astrochemistry", "astrogeology", "heliopause", "termination shock", 
  "magnetosphere", "van allen belts", "coronal mass ejection", "solar maximum", "solar minimum", "space elevator", 
  "space mining", "lunar base", "mars colonization", "venus atmosphere", "terraforming mars", "jovian planet", 
  "terrestrial planet", "ultraviolet astronomy", "infrared astronomy", "radio astronomy", "microwave background", 
  "polar vortex", "cryovolcanism", "space weather", "planetary ring", "extragalactic", "deep field", "stellar parallax", 
  "stellar classification", "y dwarf", "zodiacal light", "interplanetary dust", "asteroseismology", "circumbinary planet", 
  "gravitational waves", "redshift", "blueshift", "cepheid variable", "binary star", "trinary star", "millisecond pulsar", 
  "fast radio burst", "blazar", "hypervelocity star", "runaway star", "luminous blue variable", "tidal disruption event", 
  "galactic halo", "halo stars", "dark galaxy", "ghost galaxy", "intracluster medium", "intergalactic medium", "heliosphere", 
  "heliotail", "heliosheath", "cosmic inflation", "primordial black hole", "quintessence", "phantom energy", "string theory", 
  "brane cosmology", "cosmic void", "great attractor", "shapley supercluster", "cosmic acceleration", "stellar wind", 
  "nebular hypothesis", "proplyd", "bok globule", "herbig-haro object", "planetary differentiation", "cryogenic propulsion", 
  "solar radiation", "radiation belt", "space-time", "relativity", "gravitational collapse", "degenerate matter", "white hole", 
  "quark star", "preon star", "space-time foam", "quantum gravity", "loop quantum gravity", "holographic principle", 
  "ekpyrotic universe", "dark photon", "gravastar", "x-ray burster", "nova remnant", "cosmic rays", "synchrotron radiation", 
  "polar ring galaxy", "irregular galaxy", "low surface brightness galaxy", "hypercompact stellar system", "lensing galaxy", 
  "circumstellar disk", "ejecta blanket", "plutino", "scattered disk", "sednoid", "trans-Neptunian object", "centaur asteroid", 
  "neptune trojan", "main belt asteroid", "lunar maria", "lunar highlands", "lunar regolith", "space archaeology", "geostationary orbit", 
  "geosynchronous orbit", "polar orbit", "molniya orbit", "sun-synchronous orbit", "saros cycle", "solar neutrinos", "lunar libration", 
  "penumbral eclipse", "annular eclipse", "umbra", "precession", "chandrasekhar limit", "tolman–oppenheimer–volkoff limit", 
  "Astrophysics", "Extragalactic astronomy", "Cosmic expansion", "Dark star", "Pulsating star", "T Tauri star", "Redshift survey", 
  "Cosmic magnetism", "Galactic core", "Supermassive black hole", "Galactic bulge", "Galactic disk", "Infrared excess", "Interstellar absorption", 
  "Stellar merger", "Starburst galaxy", "Hubble's law", "Space-time curvature", "Tachyonic field", "Neutrino oscillation", 
  "Fermi paradox", "Rare Earth hypothesis", "Planetary migration", "Trojan moon", "Shepherd moon", "Magnetohydrodynamics", 
  "Super-Earth", "Mini-Neptune", "Yarkovsky effect", "Barycenter", "Astrobiological zone", "Radiative transfer", 
  "Type Ia supernova", "Type II supernova", "Wolf-Rayet star", "Stellar spectroscopy", "Adaptive optics", "Roche limit", 
  "Artificial gravity", "Planetary defense", "Quantum entanglement in space", "Cosmic neutrino background", "Gravitational shielding", 
  "X-ray spectroscopy", "Hypergalaxy", "Magnetotail", "Lunar south pole"
];
